<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:tx="http://www.springframework.org/schema/tx"
	   xmlns:aop="http://www.springframework.org/schema/aop"
	   xmlns:context="http://www.springframework.org/schema/context"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
		   http://www.springframework.org/schema/context
		   http://www.springframework.org/schema/context/spring-context-3.2.xsd
		   http://www.springframework.org/schema/aop
		   http://www.springframework.org/schema/aop/spring-aop-3.2.xsd
	   http://www.springframework.org/schema/tx
	   http://www.springframework.org/schema/tx/spring-tx-3.2.xsd">

	<!--该配置文件主要配置为扫描service包和配置事务-->

	<!--扫描注解 将该包下的带有spring注解的类加载到spring容器中-->
	<context:annotation-config></context:annotation-config>
	<context:component-scan base-package="com.nojava.service"></context:component-scan>

	<!--声明式事务管理-->
	<!--事务管理-->
	<!--事务管理器 切面 -->
	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="dynamicSourceData"/>
	</bean>
	<!--事务拦截器-->
	<!--关于事务异常回滚 默认为uncheckexception（RuntimeException +Error） ，checkexception不会滚（Exception类中除了 RuntimeException之外的类 ）  -->
	<tx:advice id="txadvice" transaction-manager="transactionManager">
		<tx:attributes>
			<!--<tx:method name="*" no-rollback-for="com.nojava.TestException"/>-->
			<tx:method name="*" propagation="REQUIRED" rollback-for="Exception"/>
			<tx:method name="find*" read-only="true"/>
		</tx:attributes>
	</tx:advice>
	<!--事务aop-->
	<aop:config proxy-target-class="true">
		<aop:pointcut id="txPointcut" expression="execution(* com.nojava.service..*.*(..))"/>
		<aop:advisor advice-ref="txadvice" pointcut-ref="txPointcut"></aop:advisor>
	</aop:config>



</beans>
